##### Default config parameters

VERBOSE=False
#### Parse by cut or by antenna
PARSE_BY='ant'
C250_FLAG=False
C250_ROTATION_OFFSET=90
MAX_GAIN_CLIPPING=30
LOC=0.1

ABSOLUTE_FLAG=False
TICK_START=-30
TICK_STOP=0
TICK_SPACING=5
TICK_STOP_SHIFT=0.2
LINE_WIDTH=2
RLIM_SHIFT=0

#ABSOLUTE_FLAG=True
#MAX_GAIN_CLIPPING=100
#TICK_STOP=20
#RLIM_SHIFT=0
