##### Default config parameters

VERBOSE=False
C250_FLAG=False
C250_ROTATION_OFFSET=90
MSIV_FLAG=True
MSIV_ROTATION_OFFSET=90
MAX_GAIN_CLIPPING=30

SIMULATE_FLAG=False
SIMULATE_SAVE=False
SIMULATE_TILT=5

ABSOLUTE_FLAG=False
TICK_POSITION=45
TICK_START=-30
TICK_STOP=0
TICK_SPACING=5
LINE_WIDTH=2
RLIM_SHIFT=0

#ABSOLUTE_FLAG=True
#MAX_GAIN_CLIPPING=100
#TICK_STOP=20
#RLIM_SHIFT=0
